# 📊 Pandas Indexing & Selection

This notebook covers:
- Column Selection
- Row Selection using `loc` and `iloc`
- Cell Selection using `loc` and `iloc`

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../DataSets/globalAirQuality.csv")

In [3]:
df.head()
df.tail()
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [4]:
#selecting data

## 🔹 Column Selection

Column selection is used to access one or more columns from a DataFrame.

### ✅ Methods:
- Using column name
- Using list of column names

In [5]:
#1 column selection

df["city"]
df[["city","aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

## 🔹 Row Selection using `loc` and `iloc`

### ✅ loc (Label-based indexing)
- Uses row labels (index names)
- Includes last value

### ✅ iloc (Integer-based indexing)
- Uses position (0,1,2,...)
- Excludes last value (like slicing)

In [6]:
#2 row selection using loc
df.loc[0]
df.loc[0:2]   #starting labelled : ending labelled (both inclusive)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [7]:
#2.1 row selection using iloc

df.iloc[0:2]  # starting index : ending index (ending index exclusive as slicing)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

## 🔹 Cell Selection using `loc` and `iloc`

Cell selection is used to access a specific value from DataFrame.

### ✅ loc
- Uses row label + column name

### ✅ iloc
- Uses row index + column index

In [8]:
#3 cell selection (row and column)

#3.1 using loc 
df.loc[0,"aqi"]
df.loc[0:2,["city","aqi"]]

       city  aqi
0  New York  108
1  New York   90
2  New York   84

In [9]:
#3.2 using iloc

df.iloc[0]
df.iloc[0:3,1:5]  # do not write like this df.iloc[0:3 , "city"] because iloc is based on index value

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [10]:
#4 selecting only single value 

df.at[0 , "city"]
df.iat[0, 1]

'US'

In [11]:
# important note

In [12]:
 cities = df["city"]
 cities[0]= "Mumbai" # doing this will change the original data because it is a view

C:\Users\sanje\AppData\Local\Temp\ipykernel_19724\362653578.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cities[0]= "Mumbai" # doing this will change the original data because it is a view

In [13]:
# to counter this problem we will use .copy to make a copy of original data where we will peerform some edits

cities = df["city"].copy()
cities[0]= "mumbai"
cities

0          mumbai
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

##  Key Differences: loc vs iloc

| Feature        | loc                     | iloc                  |
|----------------|------------------------|----------------------|
| Type           | Label-based            | Position-based       |
| Indexing       | Uses names             | Uses numbers         |
| Slice End      | Inclusive              | Exclusive            |